### ISSUE TITLE
Example of configuration file

### ISSUE THREAD

**Issue by jdelaunay** [urchade/EnriCo#1]
Dear authors,
Thanks for your Enrico article and and for granting access to your accompanying code. Might we kindly request an exemplar of the config.yaml file for utilization in model training?
Thanks,

**Comment by urchade** [comment]
hi @jdelaunay, I have added a config file

**Comment by jdelaunay** [comment]
Thank you !

**Comment by jdelaunay** [comment]
Thank you !
