### ISSUE TITLE
Span classification loss

### ISSUE THREAD

**Issue by jdelaunay** [urchade/EnriCo#2]
Dear authors,
I have been reviewing your article and noticed the discussion regarding a classification loss for spans (cf eq. 12). However, upon examining the code, specifically line 342 in the model.py file, it appears that only the loss related to the filtering process for spans is present. Could you please provide further explanation or clarification regarding the classification loss for spans mentioned in your article?

Thank you for your assistance.

Best regards,

**Comment by urchade** [comment]
Hi @jdelaunay, this repo does not implement exactly what is described in the paper. This a zero-shot version which use the gliner trick to embed relation types.

do you need the one from the paper ? It would takes some time to clean though

**Comment by urchade** [comment]
indeed, I do not perform classification on spans for now, but plans to include that in the future. I do not have dataset with entityy and relation labels for zero-shot atm

**Comment by jdelaunay** [comment]
Hi ! I would love to have the one from the paper ! Could you provide it ?

**Comment by urchade** [comment]
I can provide it but the code is messy rn. I do not have time to curate it yet

**Comment by jdelaunay** [comment]
Thanks !

**Comment by urchade** [comment]
[Archive.zip](https://github.com/urchade/EnriCo/files/15483943/Archive.zip)

here is the code @jdelaunay
